@startuml
title 현재 상황

package "Loopchain" {
    package "Loopchain Consensus" {
        [Syncer] as syncer
        [Runner] as runner
    }
    [LFT] as lft
    [PeerOuter] as outer
    () EventSystem as es
    database DB as db
    runner -up-( db

    note left of db
        BlockManager
    end note

}

() Network as network

' Relations
outer -up-> runner
runner -> syncer

syncer -up-( es
runner -up-( es
lft --( es

syncer -right-( network: ConsensusSync
outer -right-( network: Broadcasted

@enduml