@startuml
autonumber 

actor Client

box "myPeer"
    participant RestService
    participant Gunicorn
    participant Sanic

    participant ChannelService
    participant ChannelTxCreator
    participant BroadcastScheduler
    database BroadcastScheduler_Queue
end box

participant IconScoreService
control gRPC

box "otherPeer"
    database O_unconfirmedBlock_Queue
    participant O_PeerOuterService
    participant O_ChannelInnerService
    participant O_BlockManager
    participant O_ChannelStateMachine
    participant O_BroadcastScheduler
end box

== CREATE TX ==
Client -> Gunicorn: worker listens tx request
Gunicorn -> Sanic: IcxDispatcher routes request to method

' validation
Sanic -> IconScore: validate tx
IconScore -> Sanic: response

' create_icx_tx
Sanic -> ChannelTxCreator: create_icx_tx
ChannelTxCreator -> ChannelTxCreator: serialize tx
ChannelTxCreator -> ChannelTxCreator: verify tx
ChannelTxCreator -> ChannelTxCreator: pre_validate

'BroadcastScheduler
ChannelTxCreator -> BroadcastScheduler: schedule "CREATE_TX" job
BroadcastScheduler -> BroadcastScheduler_Queue: push job to queue

'---------------- check this.
ChannelTxCreator -> Sanic: response (response_code, tx_hash)
Sanic -> Sanic: check response, convert_param
Sanic -> Client: response
'---------------- check this.

== VoteUnconfirmedBlock ==
BroadcastScheduler_Queue -> gRPC: create_tx, send_tx_in_timer, send_tx_by_timer, AddTxList, make_message, then broadcast by gRPC
note over gRPC: -number-of-audience-

' Other peers
gRPC -> O_PeerOuterService: request.block
O_PeerOuterService -> O_ChannelInnerService: announced
O_ChannelInnerService -> O_BlockManager: block_loads. unpacking by its block_version and height.
O_BlockManager -> O_BlockManager: many if conditions
O_BlockManager -> O_unconfirmedBlock_Queue: many if conditions
O_BlockManager -> ChannelStateMachine: change status. LATER!
O_BlockManager -> O_BlockManager: vote_as_peer
O_BlockManager -> ScoreService..: invoke?
O_BlockManager -> O_BroadcastScheduler: send method 'VoteUnconfirmedBlock'
O_BroadcastScheduler -> OtherPeers: Broadcast. as many as they are.

== END Receive Block with VoteUnconfirmedBlock ==
note over OtherPeers: AnnounceUnconfirmedBlock. LATER!

@enduml

