@startuml

Iconist --> Gunicorn: Entry point (../api/v3/)
Dispatcher --> IconScoreStub: validation_transaction
IconScoreStub --> IconServiceEngine: some links
Dispatcher <-- IconScoreStub: response_to_json_query

Dispatcher --> ChannelTxCreatorStub: create_icx_tx
ChannelTxCreator --> TransactionSerializer: serialize with tx_version
ChannelTxCreator <-- TransactionSerializer: return Transaction Object
ChannelTxCreator --> TransactionVerifier: give Tx Object and verify it
' + pre_validate Tx...
ChannelTxCreator --> BroadcastScheduler: comm: CREATE_TX
Dispatcher <-- ChannelTxCreatorStub: response tx_hash with status code.

Iconist <-- Gunicorn: response json result..

'------------------------------------------

BroadcastScheduler --> BroadcastScheduler_Queue: schedule Broadcast order 'CREATE_TX'
BroadcastScheduler --> storedTx_Queue: put tx_item
BroadcastScheduler --> gRPC: send Tx to Peer subscribed?
gRPC --> PeerStub

@enduml
