프로세스가 여러개 떠 있으니 로그를 보고도 선후관계를 알 수가 없어.
순서는 일단 신경쓰지 말고 적어보자. 그리고 직접적인 연관 관계가 없는 것은 나중에 추리

@startuml
'========= loopchain.peer.log
partition peer_service.py
partition peer_process.py
partition container.py
partition common_subprocess.py
partition common_thread.py
partition grpc_helper.py
partition common_service.py
partition peer_service.py
partition stub_collection.py
partition common_subprocess.py
partition peer_outer_service.py
partition common_subprocess.py
partition peer_outer_service.py
partition peer_service.py
partition peer_outer_service.py
partition common_thread.py

'========= loopchain.channel.icon_dex.log
partition channel_service.py
partition statemachine.py
partition peer_manager.py
partition common_thread.py
partition broadcast_scheduler.py
partition stub_manager.py
partition __init__.py
partition grpc_helper.py
partition stub_manager.py
partition channel_service.py
partition __init__.py
partition common_thread.py
partition common_subprocess.py
partition channel_inner_service.py
partition peer_manager.py
partition stub_manager.py
partition __init__.py
partition grpc_helper.py
partition peer_manager.py
partition broadcast_scheduler.py
partition peer_manager.py
partition stub_manager.py
partition __init__.py
partition grpc_helper.py
partition peer_manager.py
partition broadcast_scheduler.py
partition peer_manager.py
partition stub_manager.py
partition peer_manager.py
partition __init__.py
partition peer_manager.py
partition grpc_helper.py
partition peer_manager.py
partition stub_manager.py
partition __init__.py
partition grpc_helper.py
partition peer_manager.py
partition stub_manager.py
partition __init__.py
partition grpc_helper.py
partition peer_manager.py
partition stub_manager.py
partition __init__.py
partition grpc_helper.py
partition peer_manager.py
partition stub_manager.py
partition broadcast_scheduler.py
partition __init__.py
partition stub_manager.py
partition __init__.py
partition grpc_helper.py
partition peer_manager.py
partition grpc_helper.py
partition peer_manager.py
partition stub_manager.py
partition peer_manager.py
partition stub_manager.py
partition __init__.py
partition grpc_helper.py
partition peer_manager.py
partition broadcast_scheduler.py
partition peer_manager.py
partition stub_manager.py
partition channel_service.py
partition __init__.py
partition channel_service.py
partition grpc_helper.py
partition channel_service.py
partition stub_manager.py
partition channel_service.py
partition epoch.py
partition broadcast_scheduler.py
partition vote.py
partition stub_manager.py
partition common_thread.py
partition __init__.py
partition core.py
partition grpc_helper.py
partition core.py
partition stub_manager.py
partition core.py
partition broadcast_scheduler.py
partition core.py
partition stub_manager.py
partition core.py
partition __init__.py
partition core.py
partition grpc_helper.py
partition core.py
partition stub_manager.py
partition core.py
partition channel_service.py
partition blockchain.py
partition peer_manager.py
partition channel_service.py
partition broadcast_scheduler.py
partition core.py
partition stub_manager.py
partition core.py
partition __init__.py
partition core.py
partition grpc_helper.py
partition timer_service.py
partition stub_manager.py
partition timer_service.py
partition core.py
partition blockchain.py
partition channel_service.py
partition blockchain.py
partition core.py
partition timer_service.py
partition core.py
partition timer_service.py
partition slot_timer.py
partition timer_service.py
partition core.py
partition consensus_siever.py
partition vote.py
partition epoch.py
partition slot_timer.py
partition timer_service.py
partition slot_timer.py
partition timer_service.py
partition consensus_siever.py
partition vote.py
partition epoch.py
partition slot_timer.py
partition timer_service.py
partition slot_timer.py
partition timer_service.py
partition consensus_siever.py
partition vote.py
partition epoch.py
partition slot_timer.py
partition timer_service.py
partition broadcast_scheduler.py
partition stub_manager.py
partition __init__.py
partition grpc_helper.py
partition broadcast_scheduler.py
partition stub_manager.py
partition broadcast_scheduler.py
partition __init__.py
partition broadcast_scheduler.py
partition stub_manager.py
partition broadcast_scheduler.py
partition stub_manager.py
partition broadcast_scheduler.py
partition grpc_helper.py
partition __init__.py
partition stub_manager.py
partition __init__.py
partition grpc_helper.py
partition __init__.py
partition broadcast_scheduler.py
partition grpc_helper.py
partition broadcast_scheduler.py
partition grpc_helper.py
partition broadcast_scheduler.py
partition timer_service.py
partition slot_timer.py
partition timer_service.py
partition consensus_siever.py
partition vote.py
partition epoch.py
partition slot_timer.py
partition timer_service.py
partition slot_timer.py
partition timer_service.py
partition consensus_siever.py
partition vote.py
partition epoch.py
partition slot_timer.py
partition timer_service.py
partition slot_timer.py
partition timer_service.py
partition consensus_siever.py
partition vote.py
partition epoch.py
partition slot_timer.py
partition timer_service.py
partition slot_timer.py
partition timer_service.py
partition consensus_siever.py
partition vote.py
partition epoch.py
partition slot_timer.py
partition timer_service.py
partition slot_timer.py
partition timer_service.py
partition consensus_siever.py
partition vote.py
partition epoch.py
partition slot_timer.py
partition timer_service.py
partition module_process.py
partition channel_service.py
partition channel_inner_service.py
partition channel_service.py
partition timer_service.py
partition channel_service.py
partition common_subprocess.py
partition channel_service.py
partition common_thread.py
partition channel_service.py
partition common_thread.py
partition channel_service.py

'========= loopchain.channel-txcreator-icon_dex_broadcast.icon_dex.log
partition broadcast_scheduler.py
partition common_thread.py
partition broadcast_scheduler.py
partition stub_manager.py
partition __init__.py
partition grpc_helper.py
partition stub_manager.py
partition broadcast_scheduler.py
partition stub_manager.py
partition __init__.py
partition grpc_helper.py
partition stub_manager.py
partition broadcast_scheduler.py
partition stub_manager.py
partition __init__.py
partition grpc_helper.py
partition stub_manager.py
partition broadcast_scheduler.py
partition stub_manager.py
partition __init__.py
partition grpc_helper.py
partition stub_manager.py
partition broadcast_scheduler.py
partition stub_manager.py
partition __init__.py
partition grpc_helper.py
partition stub_manager.py
partition broadcast_scheduler.py
partition stub_manager.py
partition __init__.py
partition grpc_helper.py
partition stub_manager.py
partition broadcast_scheduler.py
partition stub_manager.py
partition __init__.py
partition grpc_helper.py
partition stub_manager.py
partition broadcast_scheduler.py
partition common_thread.py
partition broadcast_scheduler.py
@enduml
