@startuml
'========= loopchain.peer.log
partition peer {
    (*) -> read channel manage data
    --> Launch Sanic RESTful server
    --> Run CommonService
    --> start Peer Service
    --> complete peer_init
}

partition channel {
    --> channel_service
}
partition grpc_helper {
    --> "얘는 뭐 하는거?"
}
partition channel {
    --> "뭔가 많음!"

    --> channel_inner_service
    partition peer_outer_service.py {
        --> status_update
        --> "이건 외부에서 rpc를 통해 들어오는 곳인듯. demotool 때문인가"
    }
    partition core {
        --> "뭔가 초기화"
    }
    --> channel_service init complete
    partition blockchain {
        --> re-build transaction count from DB
    }
    partition core {
        --> "뭔가 초기화"
    }
}

'================= loopchain.log
partition vote.py {
}
@endmul

