@startuml
autonumber 

actor User

User -> PeerService: $ loop peer ...
create RestService
PeerService -> RestService: execute New Process.
note over RestService: MOVE TO .. 
create ChannelService
PeerService -> ChannelService: execute New Process
note over ChannelService: MOVE TO ..
create IconScoreService 
ChannelService -> IconScoreService: execute New Process
note over IconScoreService: MOVE TO ..

@enduml
