
       ┌─┐
       ║"│
       └┬┘
       ┌┼┐
        │            ┌───────────┐
       ┌┴┐           │PeerService│
      User           └─────┬─────┘
       │ 1 $ loop peer ... │
       │ ─────────────────>│
       │                   │
       │                   │2 execute New Process. ┌───────────┐
       │                   │──────────────────────>│RestService│
       │                   │                       └─────┬─────┘
       │                   │                  ╔══════════════════════╗
       │                   │                  ║MOVE TO 'REST' digrm ░║
       │                   │                  ╚══════════════════════╝
       │                   │            3 execute New Process             ┌──────────────┐
       │                   │─────────────────────────────────────────────>│ChannelService│
       │                   │                             │                └──────┬───────┘
       │                   │                             │                  ╔════════════╗
       │                   │                             │                  ║MOVE TO .. ░║
       │                   │                             │                  ╚════════════╝
       │                   │                             │                         4 execute New Process ┌────────────────┐
       │                   │                             │                         ─────────────────────>│IconScoreService│
       │                   │                             │                       │                       └───────┬────────┘
       │                   │                             │                       │                          ╔════════════╗
       │                   │                                                                                ║MOVE TO .. ░║
      User           ┌─────┴─────┐                 ┌─────┴─────┐          ┌──────┴───────┐                  ╚════════════╝
       ┌─┐           │PeerService│                 │RestService│          │ChannelService│
       ║"│           └───────────┘                 └───────────┘          └──────────────┘
       └┬┘
       ┌┼┐
        │
       ┌┴┐

@startuml
autonumber 

actor User

User -> PeerService: $ loop peer ...
create RestService
PeerService -> RestService: execute New Process.
note over RestService: MOVE TO .. 
create ChannelService
PeerService -> ChannelService: execute New Process
note over ChannelService: MOVE TO ..
create IconScoreService 
ChannelService -> IconScoreService: execute New Process
note over IconScoreService: MOVE TO ..

@enduml
