
                                            ┌───────────┐          ┌───────────┐          ┌─────┐          ┌────────┐          ┌────────────────┐          ┌───────────────────┐          ┌────────────────────────────┐          ┌─────────────────────┐
                                            │PeerService│          │RestService│          │Sanic│          │Gunicorn│          │PeerInnerService│          │ChannelInnerService│          │ChannelTxCreatorInnerService│          │IconScoreInnerService│
                                            └─────┬─────┘          └─────┬─────┘          └──┬──┘          └───┬────┘          └───────┬────────┘          └─────────┬─────────┘          └─────────────┬──────────────┘          └──────────┬──────────┘
  ╔══════════════════════════════════════════════╗│     init &  run      │                   │                 │                       │                             │                                  │                                    │
  ║2 proc. parent-launcher and child-server_app ░║│─────────────────────>│                   │                 │                       │                             │                                  │                                    │
  ╚══════════════════════════════════════════════╝│                      │                   │                 │                       │                             │                                  │                                    │
                                                  ╔════════════════════╗ │       init        │                 │                       │                             │                                  │                                    │
                                                  ║dispatcher setting ░║ │──────────────────>│                 │                       │                             │                                  │                                    │
                                                  ╚════════════════════╝ │                   │                 │                       │                             │                                  │                                    │
                                                  │                      │                   │      binding    │                       │                             │                                  │                                    │
                                                  │                      │────────────────────────────────────────────────────────────>│                             │                                  │                                    │
                                                  │                      │                   │                 │                       │                             │                                  │                                    │
                                                  │                      │                   │                 │   binding             │                             │                                  │                                    │
                                                  │                      │──────────────────────────────────────────────────────────────────────────────────────────>│                                  │                                    │
                                                  │                      │                   │                 │                       │                             │                                  │                                    │
                                                  │                      │                   │                 │                     binding                         │                                  │                                    │
                                                  │                      │─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────>│                                    │
                                                  │                      │                   │                 │                       │                             │                                  │                                    │
                                                  │                      │                   │                 │                       │               binding       │                                  │                                    │
                                                  │                      │──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────>│
                                                  │                      │                   │                 │                       │                             │                                  │                                    │
                                                  │                      │                run│                 │                       │                             │                                  │                                    │
                                                  │                      │────────────────────────────────────>│                       │                             │                                  │                                    │
                                                  │                      │                   │                 │                       │                             │                                  │                                    │
                                                  │                      │               ╔═══╧═════════════════╧═══════════════════════╗                             │                                  │                                    │
                                                  │                      │               ║listens to world sounds and routes to Sanic ░║                             │                                  │                                    │
                                            ┌─────┴─────┐          ┌─────┴─────┐         ╚═════════════════════════════════════════════╝────────┐          ┌─────────┴─────────┐          ┌─────────────┴──────────────┐          ┌──────────┴──────────┐
                                            │PeerService│          │RestService│          │Sanic│          │Gunicorn│          │PeerInnerService│          │ChannelInnerService│          │ChannelTxCreatorInnerService│          │IconScoreInnerService│
                                            └───────────┘          └───────────┘          └─────┘          └────────┘          └────────────────┘          └───────────────────┘          └────────────────────────────┘          └─────────────────────┘

@startuml
participant PeerService
participant RestService


box "RestService"
    participant RestService
    participant Sanic 
    participant Gunicorn
end box

box "OTHER_SERVS"
    participant PeerInnerService
    participant ChannelInnerService
    participant ChannelTxCreatorInnerService
    participant IconScoreInnerService
end box

' -----------------------------
PeerService -> RestService: init &  run
note left: 2 proc. parent-launcher and child-server_app
RestService -> Sanic: init
note left: dispatcher setting

RestService -> PeerInnerService: binding 
RestService -> ChannelInnerService: binding
RestService -> ChannelTxCreatorInnerService: binding
RestService -> IconScoreInnerService: binding

RestService -> Gunicorn: run
note over Gunicorn: listens to world sounds and routes to Sanic

@enduml
