'stash
@startuml
package BroadcastScheduler {
    () Command as cmd
    database Queue
    [Handler]
    [Method]
}

() tmp_input -up-> cmd
cmd -> Queue: put Command with Callback
Queue -up-> Handler: watching
Handler -down-> Queue: get Command with Action(cb)
Handler - Method: mapping

Method -> () tmp_output
@enduml
