@startuml
participant PeerService
participant RestService


box "RestService" #ffffaa
    participant RestService
    participant Sanic 
    participant Gunicorn
end box

box "Others" #b8ffa8
    participant PeerInnerService
    participant ChannelInnerService
    participant ChannelTxCreatorInnerService
    participant IconScoreInnerService
end box

' -----------------------------
PeerService -> RestService: init &  run
note left: 2 proc. parent-launcher and child-server_app
RestService -> Sanic: init
note left: dispatcher setting

RestService -> PeerInnerService: binding 
RestService -> ChannelInnerService: binding
RestService -> ChannelTxCreatorInnerService: binding
RestService -> IconScoreInnerService: binding

RestService -> Gunicorn: run
Gunicorn -> Gunicorn: spawn workers
note over Gunicorn: listen..
[--> Gunicorn: future requests
@enduml
