@startuml
'----- Declaration
'etc
class "CommonThread" as common_thread
class "ModuleProcess" as module_process

'broadcasters
class "Broadcaster" as bc {
    - audience
    - channel

    + handle_command()
}

abstract class "Broadcastscheduler" as bc_scheduler {
    + add_schedule_listner()
    + remove_schedule_listener()
    + schedule_job()
    + schedule_broadcast()
    + reset_audience_reps_hash()
}

class "BroadcastThread" as bc_thread {
}

class "BroadcastSchedulerThread" as bc_scheduler_thread {
}

class "BroadcastSchedulerMp" as bc_scheduler_mp {
}

class "BroadcastSchedulerFactory" as bc_factory {
    + new()
}



'----- Relations
'Additional
common_thread <|-- bc_thread

'broadcast_scheduler
bc_scheduler <|. bc_scheduler_mp
bc_scheduler_thread .|> bc_scheduler

'factory
bc_scheduler_thread <.. bc_factory: new
bc_scheduler_mp <.. bc_factory: new

'Thread
bc_thread <. bc_scheduler_thread
bc <.. bc_thread

'Process
bc <. bc_scheduler_mp
module_process <.. bc_scheduler_mp

@enduml