@startuml
class "InvokeRequest" as req {
    + from_block()
}
class "PreInvokeResponse" as pre_res {
    + added_transactions
    + validators_hash
    + new(raw_response: dict)
}
class "InvokeData" as invoke_data {
    + height
    + stateHash
    + receiptsHash
    + nextValidatorsHash
    + new(raw_response: dict)
}
class "InvokePool" as invoke_pool {
    + pre_invoke(height, block_hash)
    + invoke(block)
    + genesis_invoke(block)
    + get_invoke_data(epoch_num, round_num)
}

class "BlockVoteFactory" as vote_fac
class "BlockVerifier" as verifier
class "BlockFactory" as block_fac

' Relations
invoke_pool -> block_fac: pre_invoke()
(block_fac, invoke_pool) . pre_res: RETURN of pre_invoke()
req --> verifier: INPUT of invoke()

verifier <-- invoke_pool: invoke()

invoke_pool "1" o-up- "n" invoke_data: "contains"

vote_fac <-up- invoke_pool: get_invoke_data()
(verifier, invoke_pool) . invoke_data: CREATE
invoke_data . (vote_fac, invoke_pool): POP
@enduml