@startuml
:rest_v3_req;
:request;
:pre_validate_check - req;
:get create_tcx_tx;
:append tx to tx_queue;
:resp create_icx_tx;
:rest_v3_resp;
:process_block_data_start;
:invoke block start;
:invoke req;
:invoke resp;
:invoke block done;
:confirm block start;
:save txresult;
:save tx;
:save block;
:write precommit_state req;
:write precommit_state resp;
:confirm block done;
:process_block_data done;
@enduml