
        ┌─┐
        ║"│
        └┬┘
        ┌┼┐
         │                       ┌────────┐                                 ┌─────┐                          ┌─────────┐          ┌────────────────┐          ┌──────────────────┐
        ┌┴┐                      │Gunicorn│                                 │Sanic│                          │IconScore│          │ChannelTxCreator│          │BroadcastScheduler│
      Client                     └───┬────┘                                 └──┬──┘                          └────┬────┘          └───────┬────────┘          └────────┬─────────┘
        │                            │                                         │                                  │                       │                            │
        │                            │                                         │           ╔═══════════╗          │                       │                            │
════════╪════════════════════════════╪═════════════════════════════════════════╪═══════════╣ CREATE TX ╠══════════╪═══════════════════════╪════════════════════════════╪═══════════════════════════
        │                            │                                         │           ╚═══════════╝          │                       │                            │
        │                            │                                         │                                  │                       │                            │
        │ 1 worker listens tx request│                                         │                                  │                       │                            │
        │ ───────────────────────────>                                         │                                  │                       │                            │
        │                            │                                         │                                  │                       │                            │
        │                            │ 2 IcxDispatcher routes request to method│                                  │                       │                            │
        │                            │ ────────────────────────────────────────>                                  │                       │                            │
        │                            │                                         │                                  │                       │                            │
        │                            │                                         │           3 validate tx          │                       │                            │
        │                            │                                         │ ─────────────────────────────────>                       │                            │
        │                            │                                         │                                  │                       │                            │
        │                            │                                         │            4 response            │                       │                            │
        │                            │                                         │ <─────────────────────────────────                       │                            │
        │                            │                                         │                                  │                       │                            │
        │                            │                                         │                      5 create_icx_tx                     │                            │
        │                            │                                         │ ─────────────────────────────────────────────────────────>                            │
        │                            │                                         │                                  │                       │                            │
        │                            │                                         │                                  │                       │────┐                       │
        │                            │                                         │                                  │                       │    │ <b>6</b>              │
        │                            │                                         │                                  │                       │<───┘ serialize tx          │
        │                            │                                         │                                  │                       │                            │
        │                            │                                         │                                  │                       │                            │
        │                            │                                         │                                  │                       │────┐                       │
        │                            │                                         │                                  │                       │    │ <b>7</b>              │
        │                            │                                         │                                  │                       │<───┘ verify tx             │
        │                            │                                         │                                  │                       │                            │
        │                            │                                         │                                  │                       │                            │
        │                            │                                         │                                  │                       │────┐                       │
        │                            │                                         │                                  │                       │    │ <b>8</b>              │
        │                            │                                         │                                  │                       │<───┘ pre_validate          │
        │                            │                                         │                                  │                       │                            │
        │                            │                                         │                                  │                       │                            │
        │                            │                                         │                                  │                       │   9 schedule "CREATE_TX"   │
        │                            │                                         │                                  │                       │ ───────────────────────────>
        │                            │                                         │                                  │                       │                            │
        │                            │                                         │                                  │                       │                            │────┐
        │                            │                                         │                                  │                       │                            │    │ <b>10</b>
        │                            │                                         │                                  │                       │                            │<───┘ put_command, handling
        │                            │                                         │                                  │                       │                            │
        │                            │                                         │                                  │                       │                            │
        │                            │                                         │                                  │                       │                            │
        │                            │                                         │           ╔══════════╗           │                       │                            │
════════╪════════════════════════════╪═════════════════════════════════════════╪═══════════╣ CONTINUE ╠═══════════╪═══════════════════════╪════════════════════════════╪═══════════════════════════
        │                            │                                         │           ╚══════════╝           │                       │                            │
        │                            │                                         │                                  │                       │                            │
        │                            │                                         │           11 response (response_code, tx_hash)           │                            │
        │                            │                                         │ <─────────────────────────────────────────────────────────                            │
        │                            │                                         │                                  │                       │                            │
        │                            │                                         │────┐                                                     │                            │
        │                            │                                         │    │ <b>12</b>                                           │                            │
        │                            │                                         │<───┘ check response, convert_param                       │                            │
        │                            │                                         │                                                          │                            │
        │                            │                                         │                                  │                       │                            │
        │                            │ 13 response                             │                                  │                       │                            │
        │ <─────────────────────────────────────────────────────────────────────                                  │                       │                            │
        │                            │                                         │                                  │                       │                            │
        │                            │                                         │                                  │                       │                            │
        │                            │                                         │     ╔══════════════════════╗     │                       │                            │
════════╪════════════════════════════╪═════════════════════════════════════════╪═════╣ VoteUnconfirmedBlock ╠═════╪═══════════════════════╪════════════════════════════╪═══════════════════════════
        │                            │                                         │     ╚══════════════════════╝     │                       │                            │
      Client                     ┌───┴────┐                                 ┌──┴──┐                          ┌────┴────┐          ┌───────┴────────┐          ┌────────┴─────────┐
        ┌─┐                      │Gunicorn│                                 │Sanic│                          │IconScore│          │ChannelTxCreator│          │BroadcastScheduler│
        ║"│                      └────────┘                                 └─────┘                          └─────────┘          └────────────────┘          └──────────────────┘
        └┬┘
        ┌┼┐
         │
        ┌┴┐

'stash

@startuml
autonumber 

actor Client

' myPeer
box "RestService"
    participant Gunicorn
    participant Sanic
end box

box "ScoreService"
    participant IconScore
end box

box "ChannelService"
    participant ChannelTxCreator
    participant BroadcastScheduler
    database BroadcastScheduler_Queue

end box

' otherPeer
database O_unconfirmedBlock_Queue

== CREATE TX ==
Client -> Gunicorn: worker listens tx request
Gunicorn -> Sanic: IcxDispatcher routes request to method

' validation
Sanic -> IconScore: validate tx
IconScore -> Sanic: response

' create_icx_tx
Sanic -> ChannelTxCreator: create_icx_tx
ChannelTxCreator -> ChannelTxCreator: serialize tx
ChannelTxCreator -> ChannelTxCreator: verify tx
ChannelTxCreator -> ChannelTxCreator: pre_validate

'BroadcastScheduler
ChannelTxCreator -> BroadcastScheduler: schedule "CREATE_TX" job
BroadcastScheduler -> BroadcastScheduler_Queue: push job to queue

'---------------- check this.
ChannelTxCreator -> Sanic: response (response_code, tx_hash)
Sanic -> Sanic: check response, convert_param
Sanic -> Client: response
'---------------- check this.

== VoteUnconfirmedBlock ==
BroadcastScheduler_Queue -> gRPC: create_tx, send_tx_in_timer, send_tx_by_timer, AddTxList, make_message, then broadcast by gRPC
note over gRPC: -number-of-audience-

' Other peers
gRPC -> O_PeerOuterService: request.block
O_PeerOuterService -> O_ChannelInnerService: announced
O_ChannelInnerService -> O_BlockManager: block_loads. unpacking by its block_version and height.
O_BlockManager -> O_BlockManager: many if conditions
O_BlockManager -> O_unconfirmedBlock_Queue: many if conditions
O_BlockManager -> ChannelStateMachine: change status. LATER!
O_BlockManager -> O_BlockManager: vote_as_peer
O_BlockManager -> ScoreService..: invoke?
O_BlockManager -> O_BroadcastScheduler: send method 'VoteUnconfirmedBlock'
O_BroadcastScheduler -> OtherPeers: Broadcast. as many as they are.

== END Receive Block with VoteUnconfirmedBlock ==
note over OtherPeers: AnnounceUnconfirmedBlock. LATER!

@enduml

