create PeerManager
ChannelService -> PeerManager: init

create Signer
ChannelService -> Signer: Signer, auth 등의 뭔가를 막 함 

create BroadcastScheduler
ChannelService -> BroadcastScheduler: init

create BlockManager
ChannelService -> BlockManager: init 
create NodeSubscriber
ChannelService -> NodeSubscriber: init
