@startuml
autonumber

' Groupping =========

box "Others" #ffaaaa
    entity RestService
    entity IconScoreService
    participant PeerService
end box

box "ChannelService" #93e2be
    participant ChannelService
    participant TimerService
    participant ChannelStateMachine
    participant PeerManager
    ' participant Signer
    participant BroadcastScheduler
    participant BlockManager
    ' participant NodeSubscriber
end box


box "ChannelInnerService" #ccf9f2
    participant ChannelInnerService
    participant ChannelTxCreator
    participant ChannelTxReciever
end box

' Start diagram =========
create ChannelService
...
PeerService -> ChannelService: execute New Process

'---------- CHANNEL START 
create TimerService
ChannelService -> TimerService: init
note over TimerService: investigating..
create ChannelInnerService
ChannelService -> ChannelInnerService: init.
create ChannelStateMachine
ChannelService -> ChannelStateMachine: set initial state
ChannelService -> PeerService: ask channel info detail
PeerService --> ChannelService: give channel info detail

'---------- initialize channel by detailed info
create PeerManager
ChannelService -> PeerManager: init
note over PeerManager: investigating...

' BroadcastScheduler
create BroadcastScheduler
ChannelService -> BroadcastScheduler: init
note over BroadcastScheduler: MOVE TO ..

' BlockManager
create BlockManager
ChannelService -> BlockManager: init 
note over BlockManager: MOVE TO ..

ChannelService -> RestService: bind

'---------- SCORE-A
create IconScoreService 
ChannelService -> IconScoreService: execute New Process
note over IconScoreService: MOVE TO ..
'---------- SCORE-Z

ChannelInnerService -> ChannelService: bind

'---------- Initialize Sub ServiceS 
note over ChannelInnerService: ChannelInnerService\n starts sub processes
create ChannelTxCreator
ChannelInnerService -> ChannelTxCreator: sub process 
create ChannelTxReciever
ChannelInnerService -> ChannelTxReciever: sub process
ChannelService -> BlockManager: init_epoch

'---------- finallei~
ChannelService -> TimerService: start timer
ChannelService -> ChannelStateMachine: complete_init_components

@enduml
